// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS0UaG8q7p-C7sKodH0vx13_rbt2gisE',
    appId: '1:494357121449:web:9a172a8b9b534018a69cb8',
    messagingSenderId: '494357121449',
    projectId: 'e-commerceapp-c6b2d',
    authDomain: 'e-commerceapp-c6b2d.firebaseapp.com',
    storageBucket: 'e-commerceapp-c6b2d.appspot.com',
    measurementId: 'G-6TZ9NFFS66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Jl748oTU2s9PxtiMiNVvm5JSCkZWk7o',
    appId: '1:494357121449:android:fc49ebde52c638d0a69cb8',
    messagingSenderId: '494357121449',
    projectId: 'e-commerceapp-c6b2d',
    storageBucket: 'e-commerceapp-c6b2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs15OvwPc1DKIWN9LAMoEZQJ8YT6B7nAA',
    appId: '1:494357121449:ios:0fffcf3a6a6ef182a69cb8',
    messagingSenderId: '494357121449',
    projectId: 'e-commerceapp-c6b2d',
    storageBucket: 'e-commerceapp-c6b2d.appspot.com',
    iosBundleId: 'com.ecommerce.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs15OvwPc1DKIWN9LAMoEZQJ8YT6B7nAA',
    appId: '1:494357121449:ios:f84770cae0c74465a69cb8',
    messagingSenderId: '494357121449',
    projectId: 'e-commerceapp-c6b2d',
    storageBucket: 'e-commerceapp-c6b2d.appspot.com',
    iosBundleId: 'com.ecommerce.ecommerceApp.RunnerTests',
  );
}
